-- =====================================
-- Create Audit Log Table
-- =====================================

CREATE TABLE AuditLog (
    AuditID NUMBER GENERATED BY DEFAULT AS IDENTITY,
    TransactionID NUMBER,
    LogDate DATE,
    Action VARCHAR2(100)
);

-- =====================================
-- Scenario 1
-- UpdateCustomerLastModified Trigger
-- =====================================

CREATE OR REPLACE TRIGGER UpdateCustomerLastModified
BEFORE UPDATE
ON Customers
FOR EACH ROW
BEGIN
    :NEW.LastModified := SYSDATE;
END;
/

-- =====================================
-- Scenario 2
-- LogTransaction Trigger
-- =====================================

CREATE OR REPLACE TRIGGER LogTransaction
AFTER INSERT
ON Transactions
FOR EACH ROW
BEGIN
    INSERT INTO AuditLog(
        TransactionID,
        LogDate,
        Action
    )
    VALUES(
        :NEW.TransactionID,
        SYSDATE,
        'Transaction Inserted'
    );
END;
/

-- =====================================
-- Scenario 3
-- CheckTransactionRules Trigger
-- =====================================

CREATE OR REPLACE TRIGGER CheckTransactionRules
BEFORE INSERT
ON Transactions
FOR EACH ROW

DECLARE
    v_balance NUMBER;

BEGIN

    IF :NEW.TransactionType = 'Deposit'
       AND :NEW.Amount <= 0 THEN

       RAISE_APPLICATION_ERROR(
           -20010,
           'Deposit amount must be positive'
       );

    END IF;

    IF :NEW.TransactionType = 'Withdrawal' THEN

       SELECT Balance
       INTO v_balance
       FROM Accounts
       WHERE AccountID = :NEW.AccountID;

       IF :NEW.Amount > v_balance THEN

          RAISE_APPLICATION_ERROR(
              -20011,
              'Withdrawal exceeds account balance'
          );

       END IF;

    END IF;

END;
/

-- =====================================
-- Test Scenario 1
-- =====================================

UPDATE Customers
SET Balance = 2000
WHERE CustomerID = 1;

-- =====================================
-- Test Scenario 2
-- =====================================

INSERT INTO Transactions
VALUES(
    100,
    1,
    SYSDATE,
    500,
    'Deposit'
);

-- =====================================
-- Test Scenario 3 Success
-- =====================================

INSERT INTO Transactions
VALUES(
    101,
    1,
    SYSDATE,
    100,
    'Withdrawal'
);

-- =====================================
-- Verification Queries
-- =====================================

SELECT CustomerID,
       Name,
       LastModified
FROM Customers;

SELECT *
FROM AuditLog;

SELECT *
FROM Transactions;