# Eureka Server Port
server.port=8761

# Application Name
spring.application.name=eureka-server

# Disable Eureka Client Registration or Fetching registry since this is the discovery server itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Configure log output to see service registrations
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO
